import turtle
turtle.Screen().bgcolor("green")
board=turtle.Turtle()
#first triangle of a star#
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)
board.up()
board.right(150)
board.forward(50)
#second triangle of star#
board.down()
board.right(90)
board.forward(100)
board.right(120)
board.forward(100)
board.right(120)
board.forward(100)
turtle.done()